### ISSUE TITLE
Plunker WebExtension (browser plugin)

### ISSUE THREAD

**Issue by AlexVangelov** [ggoodman/plunker-run-plugin#12]
Hi @ggoodman 

I tried to eliminate CORS restrictions for proprietary plunks with a small browser plugin. 
The more I thought about this idea, I realized that this could be a very nice and useful tool that provides some extra Plunker functionality.
A blueprint for the plugin: https://github.com/AlexVangelov/plunker-web-extension
The project is using WebExtensions standart. It will work in Chrome and Firefox > 45.
Installation link for Chrome (unlisted):
https://chrome.google.com/webstore/detail/plunker-webextension/fkaepeejnilhogogfdfnmdchiimggbdg

First task: authentication and listing user owned and favorites plunks in a quick accessible menu.
To authenticate the user I tried the following scenario:
- POST https://api.plnkr.co/sessions to create a sessionId and keep it in local storage.
- Open https://plnkr.co/auth/github in a popup and authenticate the user with the original OAuth credentials. (I have troubles providing a window.opener object from the extension... investigating)
- Listen for postMessage data of successful authentication.
  Looks like at this moment I need to:
- POST https://api.plnkr.co/sessions/:sessionId/user to assign the user to the session.
  {service: "github", token: "..."}
- List plunks, call APIs (https://api.plnkr.co/users/:username/plunks?sessid=:sessionId)

Is this the correct way?
What you think about the whole idea? 
Is it conformable with Plunker license and terms of use?

Thank you.

**Comment by ggoodman** [comment]
Hi @AlexVangelov you have done a really great job reverse-engineering the required steps.

I'm not familiar with extension development so I won't be much help w/ the `window.opener` issue.

As for License, Plunker's source is MIT. As for Terms of Use (Terms of Service) this is probably something I should draft from some reasonable template. I don't have any issue with you pursuing the development of this extension.

> eliminate CORS restrictions for proprietary plunks

What do you mean by this? In what way is the current CORS setup blocking you? What do you mean by '_proprietary plunks_'?

**Comment by AlexVangelov** [comment]
Thank you @ggoodman,
I'm talking about XMLHttpRequests to 3rd party APIs that are not CORS enabled (a feature like https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi extension). "Proprietary" I mean non public plunks.
And there are many things that this extension can provide: 
- allow file system access
- automated job scripts
- publishing scripts

Do you know that your tool is widely used by companies to share internal source examples, for interviewing job candidates and other non public purposes. I suggest you to think about enterprise paid version ;)

**Comment by AlexVangelov** [comment]
First version published.
https://chrome.google.com/webstore/detail/plunker-webextension/fkaepeejnilhogogfdfnmdchiimggbdg
So far - login, list and search user owned and favorite plunks.

Thank you.
