### ISSUE TITLE
tsconfig.json does not work, period

### ISSUE THREAD

**Issue by Asvarduil** [ggoodman/plunker-run-plugin#7]
I included a tsconfig.json file in a plunker I'm building as part of my research with integrating Angular 1.x with TypeScript.  The tsconfig.json file has instructions to compile the files to a single 'testApp.js' file.  However, when the plunker runs with a browser console open, you get 404s on the script that the transpiler is supposed to produce.

**Steps To Reproduce:**
1. Open [this plunker](http://plnkr.co/edit/4gNjHzHk42mxe0Q2COLW)*
2. Hit F12 to open a browser console.
3. Run the plunker
4. Observe that you get 404s for testApp.js.

**Expected Results:**
The transpiler should emit a file if the outFile option is used, [per the list of TypeScript compiler options](https://github.com/Microsoft/TypeScript/wiki/Compiler-Options).

**Observed Results:**
No files are emitted by the transpiler, thus the plunker does not work.

*: I'm aware that 'ctrl.someMethod()' does not exist, and that Angular isn't set up to work in the view in the first place; I've been working backwards from 'getting Angular 1.x to work with TypeScript', to 'Just getting TypeScript to work.'

**Comment by ggoodman** [comment]
Thanks for the detailed issue. I'll take a look. I haven't hopped on the typescript bandwagon quite yet so this isn't a problem I've noticed!

If you would like to try your hand at fixing this yourself, the procedure should be relatively straight-forward. You can:

```
git checkout https://github.com/ggoodman/plunker-run-plugin.git
cd plunker-run-plugin
npm install
touch config.js
npm start
```

To create/update a preview, make a `POST` request to `http://localhost:8080/randomString/test.js` with a payload like:

``` js
{
    "files": {
        "test.ts": {
            "content": "typescript file here"
        }
    }
}
```

You should be able to see any typescript compilation errors in your console. The code that transforms `.ts` --> `.js` is at: https://github.com/ggoodman/plunker-run-plugin/blob/master/adapters/transformers/typescript.js

**Comment by AlexVangelov** [comment]
A fix for this: https://github.com/ggoodman/plunker-run-plugin/pull/10
Unless I miss something.

**Comment by AlexVangelov** [comment]
But there is an issue using outFile...
Typescript compiler says: 

> Compilation error: Compilation failed: Option 'outFile' cannot be specified with option 'isolatedModules'.

Switching isolatedModules to false is jumping to another error:

> Compilation failed: Cannot find global type 'String'

Going deeper I saw that this error `diagnostic` always exists, even with successful single file compilation.
It is skipped by the transformer. (noEmitOnError: true option shows that)

So for now the fix is unusable, unless own *.d.ts files are provided.

**Comment by przemcio** [comment]
@Asvarduil Hi I open your pluker link but there wasn't too much content so I added some "very very basic things" only to test compilation etc. and it looks that the tsconfig works fine :)  here it is [a link](http://plnkr.co/edit/LYZIKikzucB3EcrBtneS?p=preview)

**Comment by shyamal890** [comment]
@przemcio I tried your plunker, it doesn't work anymore. Any ideas how to make typescript work in plunker?

**Comment by ggoodman** [comment]
@przemcio that Plunk appears to have broken Typescript syntax leading to @shyamal890 thinking typescript is unsupported.

Here is one of the official demos, shown in the embed: https://embed.plnkr.co/github/Microsoft/TypeScriptSamples/master/raytracer?preview=raytracer.html

Here is a description of how to use the system:
https://embed.plnkr.co/suu7Yg/?show=preview
