### ISSUE TITLE
Support for webpack

### ISSUE THREAD

**Issue by AlexVangelov** [ggoodman/plunker-run-plugin#9]
What you think about Webpack support?
It needs a config file, similar to existing transpilers functionality, but is quite different.

The benefit from this is the ability to build libraries including html, css images and etc. 
Finally if there is an option to register the webpacketized plunk as package, it can be reused in other plunks.

But such an unlimited expansion will need to split packages in private and public, or to create another category "libraries" to prevent disorder.

**Comment by AlexVangelov** [comment]
Just started some experimental implementation and I need advice.
Webpack input is an entry point(s) (called chunks) defined in config file (usually `webpack.config.js`). The output is also defined in there (one or more bundles).

```
output: {
    path: 'build',
    filename: '[name].js' // Template based on keys in entry above
  }
```

The desired behavior is:
- If requested js file in explicit mode is not found.
- Check if there is webpack config.
- If the config has matching output filename.
- Trigger the webpack compile process for that chunk and return the compiled bundle.

To achieve that scenario, looks like I need a transformer with 'smart' matcher.
Is this the right direction or is there a better way?

Thank you.

**Comment by ggoodman** [comment]
> The benefit from this is the ability to build libraries including html, css images and etc. 
> Finally if there is an option to register the webpacketized plunk as package, it can be reused in other plunks.

This is something I have long wanted to provide. A mechanism to author and share plunks as libraries would be a fantastic goal for Plunker.NEXT. The design of this mechanism, however would be quite tricky.

> But such an unlimited expansion will need to split packages in private and public, or to create another category "libraries" to prevent disorder.

The mechanism by which this will happen is two-fold: 1) there will be the concept of `collections` in `.NEXT` with different publication semantics; 2) there will be an explicit `release` action whereby a Plunk will have a new `semver`-based tag assigned. Getting the UX right on this will not be easy.

> Webpack input is an entry point(s) (called chunks) defined in config file (usually webpack.config.js). The output is also defined in there (one or more bundles).

I'm actually quite familiar with webpack and as you suggest, it will be difficult to do _lazy_ compilation based on webpack. Webpack is better suited for a _push_-based approach than one that is _pull_-based. I think a possible approach would be to ensure that the webpack transformer executes last if no match has yet been found. I haven't touched this code in ages and forget the details of how it is all wired together.

Another thing that is not discussed is performance. The processing required for webpack bundling is very significant (and blocking) and would have a serious impact on the latency profile for simpler jobs. I recently released [pooled-sandbox](https://github.com/ggoodman/pooled-sandbox) that would provide a mechanism to extract the processing from the main process (and even impose limits) to avoid blocking. Nevertheless, this service runs on a really minimal single-server right now and careful testing will need to be done.

**Comment by AlexVangelov** [comment]
My progress so far is to figure out that Webpack has kind of sandbox:

```
var MemoryFS = require("memory-fs");
var Webpack = require('webpack');
var fs = new MemoryFS();
// transfer files into fs...
var compiler = Webpack(options);
compiler.inputFileSystem = fs;
compiler.resolvers.normal.fileSystem = fs;
compiler.resolvers.context.fileSystem = fs;
compiler.outputFileSystem = fs;
```

Unfortunately the consumer will expect that options comes from js file rather than json (webpack rules).
So I will take a look at your https://github.com/ggoodman/pooled-sandbox :)

Also there must be a tricky way to use other transformers instead of loaders.

About performance issue... push to compile is a solution. May be this is a special case and the compiled files will appear in webpack defined build folder when it's done.

Thanks for the consent.

**Comment by AlexVangelov** [comment]
https://gist.github.com/AlexVangelov/feb5e460e9495b0f5805
